package cliutil

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type testContent struct {
	Name  string `yaml:"name"`
	Value int    `yaml:"value"`
}

func TestOutputYAML_Stdout(t *testing.T) {
	content := testContent{Name: "test", Value: 42}
	info := ContentInfo{
		Type: "TestType",
		Tool: "test-tool",
		ID:   "test-id",
		Name: "Test Name",
	}

	// Capture stdout by redirecting - but for simplicity, just verify no error
	err := OutputYAML(content, info, "")
	if err != nil {
		t.Errorf("OutputYAML to stdout failed: %v", err)
	}
}

func TestOutputYAML_File(t *testing.T) {
	tmpDir := t.TempDir()
	outputFile := filepath.Join(tmpDir, "test_output.yaml")

	content := testContent{Name: "test", Value: 42}
	info := ContentInfo{
		Type: "TestType",
		Tool: "test-tool",
		ID:   "test-id",
		Name: "Test Name",
	}

	err := OutputYAML(content, info, outputFile)
	if err != nil {
		t.Fatalf("OutputYAML to file failed: %v", err)
	}

	// Verify file was created and contains expected content
	data, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("Failed to read output file: %v", err)
	}

	output := string(data)
	if !strings.Contains(output, "# TestType generated by test-tool") {
		t.Errorf("Expected header comment, got: %s", output)
	}
	if !strings.Contains(output, "# ID: test-id") {
		t.Errorf("Expected ID comment, got: %s", output)
	}
	if !strings.Contains(output, "# Name: Test Name") {
		t.Errorf("Expected Name comment, got: %s", output)
	}
	if !strings.Contains(output, "name: test") {
		t.Errorf("Expected YAML content with name, got: %s", output)
	}
	if !strings.Contains(output, "value: 42") {
		t.Errorf("Expected YAML content with value, got: %s", output)
	}
}

func TestOutputYAML_WriteError(t *testing.T) {
	// Try to write to a non-existent directory
	content := testContent{Name: "test", Value: 42}
	info := ContentInfo{
		Type: "TestType",
		Tool: "test",
		ID:   "id",
		Name: "name",
	}

	err := OutputYAML(content, info, "/nonexistent/path/file.yaml")
	if err == nil {
		t.Error("Expected error for invalid path")
	}
	if !strings.Contains(err.Error(), "failed to write output file") {
		t.Errorf("Expected write error, got: %v", err)
	}
}
