package cliutil

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// ContentInfo provides metadata for YAML output formatting.
type ContentInfo struct {
	// Type is the content category (e.g., "Spell", "Item", "Quest").
	Type string
	// Tool is the CLI tool name that generated this content.
	Tool string
	// ID is the unique identifier of the content.
	ID string
	// Name is the display name or title of the content.
	Name string
}

// OutputYAML marshals content to YAML and writes it to a file or stdout.
// If outputFile is empty, output goes to stdout.
// Returns an error if marshaling or file writing fails.
func OutputYAML(content interface{}, info ContentInfo, outputFile string) error {
	data, err := yaml.Marshal(content)
	if err != nil {
		return fmt.Errorf("failed to marshal %s: %w", info.Type, err)
	}

	output := fmt.Sprintf("# %s generated by %s\n# ID: %s\n# Name: %s\n\n%s",
		info.Type, info.Tool, info.ID, info.Name, string(data))

	if outputFile == "" {
		fmt.Print(output)
		return nil
	}

	if err := os.WriteFile(outputFile, []byte(output), 0o644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	fmt.Printf("%s written to: %s\n", info.Type, outputFile)
	return nil
}
