/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rpc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * JSON-RPC 2.0 Endpoint
         * @description Main endpoint for all JSON-RPC method calls
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RPCRequest_move"] | components["schemas"]["RPCRequest_attack"] | components["schemas"]["RPCRequest_castSpell"] | components["schemas"]["RPCRequest_useItem"] | components["schemas"]["RPCRequest_applyEffect"] | components["schemas"]["RPCRequest_startCombat"] | components["schemas"]["RPCRequest_endTurn"] | components["schemas"]["RPCRequest_getGameState"] | components["schemas"]["RPCRequest_joinGame"] | components["schemas"]["RPCRequest_leaveGame"] | components["schemas"]["RPCRequest_createCharacter"] | components["schemas"]["RPCRequest_equipItem"] | components["schemas"]["RPCRequest_unequipItem"] | components["schemas"]["RPCRequest_getEquipment"] | components["schemas"]["RPCRequest_startQuest"] | components["schemas"]["RPCRequest_completeQuest"] | components["schemas"]["RPCRequest_updateObjective"] | components["schemas"]["RPCRequest_failQuest"] | components["schemas"]["RPCRequest_getQuest"] | components["schemas"]["RPCRequest_getActiveQuests"] | components["schemas"]["RPCRequest_getCompletedQuests"] | components["schemas"]["RPCRequest_getQuestLog"] | components["schemas"]["RPCRequest_getSpell"] | components["schemas"]["RPCRequest_getSpellsByLevel"] | components["schemas"]["RPCRequest_getSpellsBySchool"] | components["schemas"]["RPCRequest_getAllSpells"] | components["schemas"]["RPCRequest_searchSpells"] | components["schemas"]["RPCRequest_getObjectsInRange"] | components["schemas"]["RPCRequest_getObjectsInRadius"] | components["schemas"]["RPCRequest_getNearestObjects"] | components["schemas"]["RPCRequest_generateContent"] | components["schemas"]["RPCRequest_regenerateTerrain"] | components["schemas"]["RPCRequest_generateItems"] | components["schemas"]["RPCRequest_generateLevel"] | components["schemas"]["RPCRequest_generateQuest"] | components["schemas"]["RPCRequest_getPCGStats"] | components["schemas"]["RPCRequest_validateContent"];
                };
            };
            responses: {
                /** @description Successful RPC response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RPCResponse_move"] | components["schemas"]["RPCResponse_attack"] | components["schemas"]["RPCResponse_generic"];
                    };
                };
                400: components["responses"]["InvalidRequest"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RPCRequest: {
            /** @enum {string} */
            jsonrpc: "2.0";
            /** @description The RPC method name */
            method: string;
            /** @description Method-specific parameters */
            params: Record<string, never>;
            /** @description Unique request identifier for matching responses */
            id: string | number;
        };
        RPCResponse: {
            /** @enum {string} */
            jsonrpc: "2.0";
            id: string | number;
            /** @description Response data (present on success) */
            result?: Record<string, never>;
            error?: components["schemas"]["RPCError"];
        };
        RPCError: {
            /**
             * @description Error code:
             *     -32700: Parse error
             *     -32600: Invalid Request
             *     -32601: Method not found
             *     -32602: Invalid params
             *     -32603: Internal error
             */
            code: number;
            message: string;
            /** @description Additional error information */
            data?: Record<string, never>;
        };
        Position: {
            /** @description X coordinate */
            x: number;
            /** @description Y coordinate */
            y: number;
        };
        Rectangle: {
            min_x: number;
            min_y: number;
            max_x: number;
            max_y: number;
        };
        /** @enum {string} */
        CharacterClass: "fighter" | "mage" | "cleric" | "thief" | "ranger" | "paladin";
        /** @enum {string} */
        AttributeMethod: "roll" | "pointbuy" | "standard" | "custom";
        RPCRequest_move: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "move";
            params?: {
                /** @description Player session identifier */
                session_id: string;
                /**
                 * @description Direction of movement
                 * @enum {string}
                 */
                direction: "north" | "south" | "east" | "west" | "n" | "s" | "e" | "w";
            };
        };
        RPCResponse_move: components["schemas"]["RPCResponse"] & {
            result?: {
                success: boolean;
                position: components["schemas"]["Position"];
            };
        };
        RPCRequest_attack: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "attack";
            params?: {
                /** @description Player session identifier */
                session_id: string;
                /** @description Target entity identifier */
                target_id: string;
                /** @description Weapon being used for attack */
                weapon_id: string;
            };
        };
        RPCResponse_attack: components["schemas"]["RPCResponse"] & {
            result?: {
                success: boolean;
                /** @description Damage dealt */
                damage?: number;
                /** @description Attack roll result */
                attack_roll?: number;
            };
        };
        RPCRequest_castSpell: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "castSpell";
            params?: {
                session_id: string;
                /** @description Spell identifier */
                spell_id: string;
                /** @description Target entity (optional for area spells) */
                target_id: string;
                /** @description Target position (optional, for area effect spells) */
                position?: components["schemas"]["Position"];
            };
        };
        RPCResponse_castSpell: components["schemas"]["RPCResponse"] & {
            result?: {
                success?: boolean;
                spell_id?: string;
                /** @description Spell effect results */
                effect?: Record<string, never>;
            };
        };
        RPCRequest_useItem: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "useItem";
            params?: {
                session_id: string;
                item_id: string;
                /** @description Optional target for item use */
                target_id?: string;
            };
        };
        RPCRequest_applyEffect: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "applyEffect";
            params?: {
                session_id: string;
                /** @description Type of status effect */
                effect_type: string;
                target_id: string;
                /** @description Strength/amount of effect */
                magnitude: number;
                /** @description Duration in game time units */
                duration: number;
            };
        };
        RPCRequest_startCombat: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "startCombat";
            params?: {
                session_id: string;
                /** @description Array of participant entity IDs */
                participant_ids: string[];
            };
        };
        RPCResponse_startCombat: components["schemas"]["RPCResponse"] & {
            result?: {
                success: boolean;
                /** @description Ordered participant IDs based on initiative */
                initiative: string[];
                /** @description ID of first participant to act */
                first_turn: string;
            };
        };
        RPCRequest_endTurn: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "endTurn";
            params?: {
                session_id: string;
            };
        };
        RPCResponse_endTurn: components["schemas"]["RPCResponse"] & {
            result?: {
                success: boolean;
                /** @description ID of next participant to act */
                next_turn: string;
            };
        };
        RPCRequest_getGameState: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getGameState";
            params?: {
                session_id: string;
            };
        };
        RPCResponse_getGameState: components["schemas"]["RPCResponse"] & {
            result?: {
                player?: {
                    position?: components["schemas"]["Position"];
                    stats?: {
                        hp?: number;
                        max_hp?: number;
                        level?: number;
                        experience?: number;
                    };
                    effects?: Record<string, never>[];
                    inventory?: Record<string, never>[];
                    spells?: Record<string, never>[];
                };
                world?: {
                    visible_objects?: Record<string, never>[];
                    current_time?: string;
                    combat_state?: Record<string, never> | null;
                };
            };
        };
        RPCRequest_joinGame: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "joinGame";
            params?: {
                /** @description Display name for the player */
                player_name: string;
            };
        };
        RPCResponse_joinGame: components["schemas"]["RPCResponse"] & {
            result?: {
                success: boolean;
                /** @description Session ID for subsequent requests */
                session_id: string;
            };
        };
        RPCRequest_leaveGame: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "leaveGame";
            params?: {
                session_id: string;
            };
        };
        RPCRequest_createCharacter: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "createCharacter";
            params?: {
                /** @description Character name */
                name: string;
                class: components["schemas"]["CharacterClass"];
                attribute_method: components["schemas"]["AttributeMethod"];
                /** @description Custom attribute values (required if attribute_method is 'custom') */
                custom_attributes?: {
                    [key: string]: number;
                };
                /** @default true */
                starting_equipment: boolean;
                /** @default 100 */
                starting_gold: number;
            };
        };
        RPCResponse_createCharacter: components["schemas"]["RPCResponse"] & {
            result?: {
                success: boolean;
                session_id: string;
                /** @description Created character data */
                character?: Record<string, never>;
                /** @description Player data */
                player?: Record<string, never>;
                errors?: string[];
                warnings?: string[];
                creation_time?: string;
                generated_stats?: Record<string, never>;
                starting_items?: Record<string, never>[];
            };
        };
        RPCRequest_equipItem: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "equipItem";
            params?: {
                session_id: string;
                item_id: string;
                /** @enum {string} */
                slot: "head" | "neck" | "chest" | "hands" | "rings" | "legs" | "feet" | "weapon_main" | "weapon_off" | "main_hand" | "off_hand";
            };
        };
        RPCResponse_equipItem: components["schemas"]["RPCResponse"] & {
            result?: {
                success?: boolean;
                message?: string;
                equipped_item?: Record<string, never>;
                previous_item?: Record<string, never> | null;
            };
        };
        RPCRequest_unequipItem: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "unequipItem";
            params?: {
                session_id: string;
                slot: string;
            };
        };
        RPCRequest_getEquipment: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getEquipment";
            params?: {
                session_id: string;
            };
        };
        RPCResponse_getEquipment: components["schemas"]["RPCResponse"] & {
            result?: {
                success?: boolean;
                equipment?: {
                    [key: string]: Record<string, never>;
                };
                total_weight?: number;
                equipment_bonuses?: Record<string, never>;
            };
        };
        RPCRequest_startQuest: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "startQuest";
            params?: {
                session_id: string;
                /** @description Quest object containing quest data */
                quest: Record<string, never>;
            };
        };
        RPCRequest_completeQuest: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "completeQuest";
            params?: {
                session_id: string;
                quest_id: string;
            };
        };
        RPCRequest_updateObjective: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "updateObjective";
            params?: {
                session_id: string;
                quest_id: string;
                /** @description 0-based objective index */
                objective_index: number;
                /** @description New progress value */
                progress: number;
            };
        };
        RPCRequest_failQuest: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "failQuest";
            params?: {
                session_id: string;
                quest_id: string;
            };
        };
        RPCRequest_getQuest: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getQuest";
            params?: {
                session_id: string;
                quest_id: string;
            };
        };
        RPCRequest_getActiveQuests: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getActiveQuests";
            params?: {
                session_id: string;
            };
        };
        RPCRequest_getCompletedQuests: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getCompletedQuests";
            params?: {
                session_id: string;
            };
        };
        RPCRequest_getQuestLog: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getQuestLog";
            params?: {
                session_id: string;
            };
        };
        RPCRequest_getSpell: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getSpell";
            params?: {
                spell_id: string;
            };
        };
        RPCRequest_getSpellsByLevel: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getSpellsByLevel";
            params?: {
                /** @description Spell level (0 for cantrips) */
                level: number;
            };
        };
        RPCRequest_getSpellsBySchool: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getSpellsBySchool";
            params?: {
                /** @description Magic school name */
                school: string;
            };
        };
        RPCRequest_getAllSpells: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getAllSpells";
            params?: Record<string, never>;
        };
        RPCRequest_searchSpells: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "searchSpells";
            params?: {
                /** @description Search query string */
                query: string;
            };
        };
        RPCRequest_getObjectsInRange: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getObjectsInRange";
            params?: {
                session_id: string;
                min_x: number;
                min_y: number;
                max_x: number;
                max_y: number;
            };
        };
        RPCRequest_getObjectsInRadius: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getObjectsInRadius";
            params?: {
                session_id: string;
                center_x: number;
                center_y: number;
                radius: number;
            };
        };
        RPCRequest_getNearestObjects: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getNearestObjects";
            params?: {
                session_id: string;
                center_x: number;
                center_y: number;
                /** @description Number of nearest objects to return */
                k: number;
            };
        };
        RPCRequest_generateContent: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "generateContent";
            params?: {
                session_id: string;
                /** @enum {string} */
                content_type: "terrain" | "items" | "levels" | "quests";
                location_id: string;
                /** @default 5 */
                difficulty: number;
                constraints?: {
                    [key: string]: unknown;
                };
            };
        };
        RPCRequest_regenerateTerrain: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "regenerateTerrain";
            params?: {
                session_id: string;
                location_id: string;
                /** @default 50 */
                width: number;
                /** @default 50 */
                height: number;
                /** @default forest */
                biome_type: string;
                /** @default 0.5 */
                density: number;
                /** @default 0.3 */
                water_level: number;
                /** @default moderate */
                connectivity: string;
            };
        };
        RPCRequest_generateItems: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "generateItems";
            params?: {
                session_id: string;
                location_id: string;
                /** @default 3 */
                count: number;
                /** @default common */
                min_rarity: string;
                /** @default rare */
                max_rarity: string;
                /** @default 5 */
                player_level: number;
                item_types?: string[];
            };
        };
        RPCRequest_generateLevel: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "generateLevel";
            params?: {
                session_id: string;
                /** @default 50 */
                width: number;
                /** @default 50 */
                height: number;
                /** @default 8 */
                room_count: number;
                /** @default classic */
                theme: string;
                /** @default 5 */
                difficulty: number;
                /** @default straight */
                corridor_style: string;
            };
        };
        RPCRequest_generateQuest: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "generateQuest";
            params?: {
                session_id: string;
                /** @default fetch */
                quest_type: string;
                /** @default 5 */
                difficulty: number;
                /** @default 1 */
                min_objectives: number;
                /** @default 3 */
                max_objectives: number;
                /** @default common */
                reward_tier: string;
                /** @default linear */
                narrative_type: string;
            };
        };
        RPCRequest_getPCGStats: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "getPCGStats";
            params?: {
                session_id: string;
            };
        };
        RPCRequest_validateContent: components["schemas"]["RPCRequest"] & {
            /** @constant */
            method?: "validateContent";
            params?: {
                session_id: string;
                content_type: string;
                content: Record<string, never>;
                /** @default false */
                strict: boolean;
            };
        };
        RPCResponse_generic: components["schemas"]["RPCResponse"] & {
            result?: {
                success?: boolean;
                message?: string;
                data?: Record<string, never>;
            };
        };
    };
    responses: {
        /** @description Invalid RPC request format or parameters */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RPCError"];
            };
        };
        /** @description Server error during RPC processing */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RPCError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
